#!/usr/bin/env bash
# Installs Nginx on my web server

#Update the package list
apt-get update
# Install Nginx
apt-get install -y nginx
# Create the HTML directory (and parent directories if needed)
mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
# Configure Nginx to listen on port 80
echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default
service nginx restart
