#!/usr/bin/env bash
#This script displays best school and hi using a while loop

count=1
while [ $count -le 10 ]
do
	echo "Best School"
	count=$((count + 1))
	if [ $count -eq 9 ]
	then
		echo Hi
	fi
done
